version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: docker-compose/Dockerfile
    image: travellist
    container_name: tap_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tap

  db:
    image: mysql:latest
    container_name: tap_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - tap
  adminer:
    image: adminer
    restart: always
    ports:
      - 7232:8080
    volumes:
      - ./docker-compose/adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - tap

  nginx:
    image: nginx:latest
    container_name: tap_nginx
    restart: unless-stopped
    ports:
      - 8020:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tap

networks:
  tap:
    driver: bridge
